### ISSUE TITLE
Better example for v2

### ISSUE THREAD

**Issue by winchell** [nicksnyder/go-i18n#101]
Could you make a more thorough example for V2? 

I'm not sure why NewBundle accepts `language.English` when later `Accept-Language` is used as an input. What is a bundle, for that matter? 

`RegisterUnmarshalFunc` is set to `toml`. Where is there any TOML used?

**Comment by nicksnyder** [comment]
I do think there are improvements I can and should make to the doc in the README. I think a few of your questions are answered by the package documentation. Did you read that?

> I'm not sure why NewBundle accepts language.English

https://godoc.org/github.com/nicksnyder/go-i18n/v2/i18n#NewBundle

It is the default language for your application.

> later Accept-Language is used as an input.

https://godoc.org/github.com/nicksnyder/go-i18n/v2/i18n#NewLocalizer

> What is a bundle, for that matter?

https://godoc.org/github.com/nicksnyder/go-i18n/v2/i18n#Bundle

> Where is there any TOML used?

<img width="676" alt="screen shot 2018-05-02 at 8 57 57 pm" src="https://user-images.githubusercontent.com/754768/39559516-b3c8d714-4e4b-11e8-8f6a-11fad936dc5a.png">

**Comment by winchell** [comment]
Thanks! 

So, `v2/example/main.go` does ```localizer.MustLocalize(&i18n.LocalizeConfig{
			DefaultMessage: &i18n.Message{
				ID:          "UnreadEmails",
				Description: "The number of unread emails a person has",
				One:         "I have {{.PluralCount}} unread email.",
				Other:       "I have {{.PluralCount}} unread emails.",
			}...```

The TOML files -- in the example -- aren't using a .toml file. Right? I could just be missing something.

PS the links in the README are pointing to the old examples.

**Comment by nicksnyder** [comment]
> the links in the README are pointing to the V1 examples.

Thanks for reporting! Fixed in https://github.com/nicksnyder/go-i18n/commit/481274b90e8b730c4720ee7f3c70b2f650e83ba0.

> The TOML files -- in the example -- aren't using a .toml file. Right?

You are right. I meant to add an example TOML file for another language but forgot. I will update that example.

**Comment by nicksnyder** [comment]
Going to close this. Let me know if you have any other suggestions for doc improvements.
