### ISSUE TITLE
Tag format for pre-release versions does not follow semantic versioning standard breaking the "dep" tool

### ISSUE THREAD

**Issue by ray-harris** [nicksnyder/go-i18n#104]
The `dep` tool is becoming the standard mechanism for managing dependencies in go. It follows the semantic versioning rules outlined in https://semver.org

Current in the project, there are two pre-release tags, `v2.0.0.beta.1` and `v2.0.0.beta.2`, but they don't follow the semver rules. They should be `v2.0.0-beta.1` and `v2.0.0-beta.2` instead.

Not following the semver rules causes `dep` to break when trying to use these versions. The only way to get it to work is to pin the exact branch using the `revision` constraint instead of the `version` constraint.

Recommend committing a tag such as `v2.0.0-beta.2` to allow dependency management with dep during pre-release.

This is the revision constraint that works but doesn't allow upgrading to a newer version when it's released:

```
[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  revision = "v2.0.0.beta.2"
```

This would be the preferred way of specifying the constraint using version:

```
[[constraint]]
  name = "github.com/nicksnyder/go-i18n"
  version = "v2.0.0-beta.2"
```

Thanks

**Comment by nicksnyder** [comment]
Oops! This was not intentional and I will fix.

**Comment by nicksnyder** [comment]
I tagged a new release v2.0.0-beta.3 and added proper tags for the previous releases.
