### ISSUE TITLE
Specific pluralities other than zero, one and two

### ISSUE THREAD

**Issue by dotboris** [nicksnyder/go-i18n#112]
Currently the pluralizations only support:

- Zero
- One
- Two
- Few
- Many
- Other

I have a case where I need to translate something in a specific way when there's 3 items. When I try to do that I get an error because `three` is not a valid plurality.

Ideally, someone should be able to just specify a translation for any specific number of items.

**Comment by nicksnyder** [comment]
What you are describing is application level logic that is unrelated to pluralization rules for a given language (and therefore out of scope for this library). Note that the pluralization categories do not map to numbers either so you can’t assume that category “one” maps to the number 1 in an arbitrary language.

If you have messages that need to be displayed for specific values, the you need to special case them in your application logic.

```go
if x == 3 {
    // special message for 3
} else {
    // regular message
}
```
