### ISSUE TITLE
Update `package:yaml` in go.mod

### ISSUE THREAD

**Issue by roylee0704** [nicksnyder/go-i18n#116]
Hey Nick! :)

I'm getting the following error while trying to `vgo mod -vendor` your package:

```sh
vgo mod -vendor
go: github.com/nicksnyder/go-i18n/v2@v2.0.0-beta.3: parsing go.mod: go.mod:6: invalid module: gopkg.in/yaml.v2 should be .v2, not v1 (v1.2.1-gopkgin-v2.2.1)
```

You might want to consider regenerate `go.mod` file with latest `go1.10.3`, and then create a new release tag :)

Detailed to the issue: https://github.com/golang/go/issues/24099

--- 

_p/s: I have tried it, it will resolve the issue mentioned above :)_

**Comment by nicksnyder** [comment]
Thanks for reporting, will fix!

**Comment by roylee0704** [comment]
Hey you left out `/v2` ;) I submitted a PR(#118 ) to fix that for you
