### ISSUE TITLE
Odd behaviour with DefaultMessage

### ISSUE THREAD

**Issue by bep** [nicksnyder/go-i18n#125]
Working on https://github.com/gohugoio/hugo/pull/5243 and trying to find a workaround for #124 I found some odd behaviour with `DefaultMessage`
```go
translated, err := localizer.Localize(&i18n.LocalizeConfig{
				//DefaultMessage: defaultMessage,
				MessageID:    translationID,
				TemplateData: templateData,
			})
```

I have a test case which returns `translated` as expected and no error with the code above. If I uncomment the `DefaultMessage`, I always get the default message in return.

**Comment by nicksnyder** [comment]
I don't understand the issue you are reporting and what you expected to happen. Can you clarify?

**Comment by bep** [comment]
* My intuition says that `DefaultMessage` is the message returned when no match can be found in the bundle with `translationID`. This way I can use that to determine if a string is considered untranslated.
* What I'm seeing instead is that if `DefaultMessage` is provided, that is what I always get.

**Comment by bep** [comment]
This is approximately my failing case:

```go
func TestLocalizer_DefaultMessage(t *testing.T) {
	en := "[hello]\nother = \"Hello, World!\""
	es := "[hello]\nother = \"¡Hola, Mundo!\""
	bndl := &Bundle{DefaultLanguage: language.English}
	bndl.RegisterUnmarshalFunc("toml", toml.Unmarshal)

	_, err := bndl.ParseMessageFileBytes([]byte(en), "en.toml")
	if err != nil {
		t.Fatal(err)
	}
	_, err = bndl.ParseMessageFileBytes([]byte(es), "es.toml")
	if err != nil {
		t.Fatal(err)
	}

	var defaultMessage = &Message{
		ID:    "___I18N_DEFAULT",
		Other: "I18N_MISSING",
	}

	_ = defaultMessage

	localizer := NewLocalizer(bndl, "es")

	translated, err := localizer.Localize(&LocalizeConfig{
		DefaultMessage: defaultMessage,
		MessageID:      "hello",
	})

	if err != nil {
		t.Fatal(err)
	}

	if translated != "¡Hola, Mundo!" {
		t.Fatalf("Got %s, expected %s", translated, "¡Hola, Mundo!")
	}

}
```

If fails with:

```bash
 Got I18N_MISSING, expected ¡Hola, Mundo!
```

This test, however, passes:

```go
func TestLocalizer_DefaultMessage(t *testing.T) {
	en := "[hello]\nother = \"Hello, World!\""
	es := "[hello]\nother = \"¡Hola, Mundo!\""
	bndl := &Bundle{DefaultLanguage: language.English}
	bndl.RegisterUnmarshalFunc("toml", toml.Unmarshal)

	_, err := bndl.ParseMessageFileBytes([]byte(en), "en.toml")
	if err != nil {
		t.Fatal(err)
	}
	_, err = bndl.ParseMessageFileBytes([]byte(es), "es.toml")
	if err != nil {
		t.Fatal(err)
	}

	var defaultMessage = &Message{
		ID:    "___I18N_DEFAULT",
		Other: "I18N_MISSING",
	}

	_ = defaultMessage

	localizer := NewLocalizer(bndl, "es")

	translated, err := localizer.Localize(&LocalizeConfig{
		//DefaultMessage: defaultMessage,
		MessageID: "hello",
	})

	if err != nil {
		t.Fatal(err)
	}

	if translated != "¡Hola, Mundo!" {
		t.Fatalf("Got %s, expected %s", translated, "¡Hola, Mundo!")
	}

}
```

The only difference is that I don't send in the `DefaultMessage` to `Localize`.

**Comment by nicksnyder** [comment]
Thanks for providing a test case! I will take a look later today hopefully.

**Comment by nicksnyder** [comment]
Ok I see what the problem is. I never intended `DefaultMessage` to be used at the same time as `MessageID`. See the documentation here: https://github.com/nicksnyder/go-i18n/blob/master/v2/i18n/localizer.go#L49

What made you want to specify `DefaultMessage`?

Like I said in https://github.com/nicksnyder/go-i18n/issues/125#issuecomment-423971513, providing a `DefaultMessage` means you will always get a translation.

**Comment by bep** [comment]
>What made you want to specify DefaultMessage?

See #124

The way `DefaultMessage` works in the test case above does not make sense to. I have looked at it several times, it still does not make sense.

> providing a DefaultMessage means you will always get a translation.

Sure, which was my motivation for doing the above. But I think that if you ask 100 persons, at least 99 of them will agree with me if I say: I expect`DefaultMessage` to be the value you get when no message could be found by a given ID. This makes sure that "you will always get a translation". If you always return the `DefaultMessage`, why is it called `DefaultMessage` and why would I  bother to invoke  `localizer.Localize` if I already had the answer?

**Comment by nicksnyder** [comment]
> See #124

So you wanted to use `DefaultMessage` as a workaround for not having MessageNotFoundErr exported?

> But I think that if you ask 100 persons, at least 99 of them will agree with me if I say: I expectDefaultMessage to be the value you get when no message could be found by a given ID. This makes sure that "you will always get a translation".

This is exactly how it works. I think I understand why you are confused though, so let me walk you through what is happening in the failing test case.

```
var defaultMessage = &Message{
	ID:    "___I18N_DEFAULT",
	Other: "I18N_MISSING",
}

translated, err := localizer.Localize(&LocalizeConfig{
	// You are asking to localize the message with id "___I18N_DEFAULT"
	// Because there are no translations for "___I18N_DEFAULT" in the bundle, it always returns the default value "I18N_MISSING"
	DefaultMessage: defaultMessage,
	MessageID:      "hello", // this is ignored because you are passing DefaultMessage
})
```

Basically, it is not valid to set both `DefaultMessage` and `MessageID` at the same time. I can/should update Localize to return an error in this case.

**Comment by bep** [comment]
I have now found some time to revisit this. Even with `MessageNotFoundErr` I cannot seem to find a way to get the "v1 behavior", and since I suspect this would be a common requirement, I think you should consider it:

* If I look up `hello` for `es` (Spanish), and `hello` isn't translated into Spanish, I get some other translation. I only get the above error for totally untranslated strings. And since what I get is a string, I have no way of knowing if what I get is in the language I asked for (I tried to read the documentation).
*  This is mainly motivated by maintenance (I want to alert the user that there is a missing translation), but I may also want to control the "fall back" language (English, possibly). I have not looked into how you decide that today.

Some suggestions would be:

1. Add a way to get the returned language in `Localize`.
2. It would also be nice to have some control of the "language fall back order" in 1), but if the language you get is known, that logic may somehow be implemented by the caller.

**Comment by nicksnyder** [comment]
> If I look up hello for `es` (Spanish), and hello isn't translated into Spanish, I get some other translation.

v1 was pretty dumb and only returned the language tag that you asked for (or the longest prefix of that tag that was available).

v2 delegates this logic to golang.org/x/text which does proper fallback matching and will choose the best available language to display to the user, if any.

> I may also want to control the "fall back" language (English, possibly). I have not looked into how you decide that today.

> It would also be nice to have some control of the "language fall back order" in 1), but if the language you get is known, that logic may somehow be implemented by the caller.

The language fallback order is determined by the order of tags passed to `NewLocalizer` (or weights if you pass it an Accept-Language header). This fallback logic is controlled in a standard way by golang.org/x/text

> Add a way to get the returned language in Localize.

Is this sufficient https://github.com/nicksnyder/go-i18n/pull/139

**Comment by bep** [comment]
>Is this sufficient #139

Yes.
