### ISSUE TITLE
Nested .yml file

### ISSUE THREAD

**Issue by maeglindeveloper** [nicksnyder/go-i18n#135]
Hi everyone, 

I'm actually trying to use the `MustLocalize(...)` method to load message defined in a .yml language file.
I have a doubt  regarding the ability to load nested yml messages as follow

**en.yml** file:
```
mysection:
  title: my title
  content: my content
```
using that main function:

```
func main() {
	bundle := &i18n.Bundle{DefaultLanguage: language.English}
	bundle.RegisterUnmarshalFunc("yml", yaml.Unmarshal)
	bundle.MustLoadMessageFile("en.yml")

	localizer := i18n.NewLocalizer(bundle, "en")

	title := localizer.MustLocalize(&i18n.LocalizeConfig{MessageID: "mysection.title"})
	content := localizer.MustLocalize(&i18n.LocalizeConfig{MessageID: "mysection.content"})

        ...
```
It fails saying that **mysection.title** is not found.

The only way I found is to have something like that:

**en.yml** file:
```
mysection_title: my title
mysection_content: my content
```
and 
```
	title := localizer.MustLocalize(&i18n.LocalizeConfig{MessageID: "mysection_title"})
	content := localizer.MustLocalize(&i18n.LocalizeConfig{MessageID: "mysection_content"})
```

Maybe I did it wrong :s.
Any thoughts ?
Thanks in advance
@nicksnyder

**Comment by nicksnyder** [comment]
A translation file is just keys and values. No nesting is supported.

You can use comments or you can use separate files to group your translations.

See also https://github.com/nicksnyder/go-i18n/issues/121
