### ISSUE TITLE
goi18n extract does not see messages with concatenations

### ISSUE THREAD

**Issue by VadimKulagin** [nicksnyder/go-i18n#142]
I have such an expression in the code and the `goi18n extract` (v2) does not see it:

```go
	SomeID = &i18n.Message{
		ID: "Some ID",
		Other: "One" + "Two",
	}
```

**Comment by nicksnyder** [comment]
Yeah, it only looks for string literals:
https://github.com/nicksnyder/go-i18n/blob/0ebaecb8e23486f0194b1c19517739bd78317583/v2/goi18n/extract_command.go#L170-L176

Are you concatenating for line length reasons?

**Comment by VadimKulagin** [comment]
Yes. In fact, I have a very long string, so I want to divide it into several parts.

**Comment by VadimKulagin** [comment]
Do you plan to add support for strings with concatenation? This would be convenient when working with long lines in the code.
