### ISSUE TITLE
How to handle unknown languages?

### ISSUE THREAD

**Issue by bep** [nicksnyder/go-i18n#146]
In v1 it was possible to handle "custom languages" by registering a new plural spec based on the english one.

In v2, the language handling is a little bit more unclear (hidden).

If I try to parse a language file with the name `klingon.toml`:

```go
m, err := bundle.ParseMessageFileBytes([]byte("[hello]\nother = \"nuqneH\""), "klingon.toml")
```

I get a `Message` with `language.Undefined` in return. This sounds like an `error` to me, but my main challenge here is: How do I define a new language? I have tried to read up on how `golang.org/x/text/language` works, but I cannot find a way to register a new language.

See https://github.com/gohugoio/hugo/issues/5242

**Comment by nicksnyder** [comment]
I agree that this should be supported; just need to figure out how to make it work in conjunction with x/text

**Comment by nicksnyder** [comment]
Use the language tag `art-x-klingon` on the latest master.
