### ISSUE TITLE
goi18n extract doesn't see non-explicit i18n.Message items

### ISSUE THREAD

**Issue by fgm** [nicksnyder/go-i18n#148]
In this example : https://play.golang.org/p/16bxvOrgURu

The individual `&i18n.Message` types on the array items are not needed and linting suggest to remove them, since they are already explicit from the array item type.

However, when removed, `goi18n extract` no longer sees the messages, so they have to be kept.

**Comment by nicksnyder** [comment]
Yeah, extract just [walks the AST](
https://github.com/nicksnyder/go-i18n/blob/master/v2/goi18n/extract_command.go#L150) looking for message literals. It is probable possible to add a code path to handle messages nested in a slice (or map), or maybe even just relax this constraint to match any struct literal that looks like a message.

Can you clarify your use case for storing messages in a slice?

**Comment by fgm** [comment]
In the case for which I discovered it I have a custom `error`-implementing type in the core domain, and UIs (e.g. web) need to expose localized versions of the error messages. 

So there is a map (not an array as in the playground example) of predefined errors, each of which includes an english source message (string) field, and these errors are keyed in the map by an error constant, and code only handles these error constant until a needs arises to represent them in the user context, e.g. the web handler for a request.

I can probably tweak the code to use the mechanism you explained on  #137 instead, though.
