### ISSUE TITLE
internal.unmarshalInterface() tries to use leftDelim/rightDelim as lowercase

### ISSUE THREAD

**Issue by fgm** [nicksnyder/go-i18n#149]
Func `unmarshalInterface(v interface{})` unmarshals message values based on the lowercase versions of the keys found in the message data.

For most keys, the case value is indeed lower-case, but there are two exceptions: `leftDelim` and `rightDelim`, which can never be matched by the output of `strings.ToLower()`, and this prevents delimiters present in message files from being unserialized. As a consequence, translated messages are loaded without their delimiter specifications, which causes `Localize()` to return the message plural form untemplated instead of applying the template, which is only used when falling back to the `DefaultMessage`.

See https://github.com/nicksnyder/go-i18n/blob/master/v2/internal/message.go#L80
## Suggested fix

Replace `leftDelim` and `rightDelim` by `leftdelim` and `rightdelim`.

**Comment by fgm** [comment]
Also, as a related issue, it would be nice if the loaded messages could inherit the values from the `DefaultMessage` instead of having to add the manually to each templated message, but that's a more complex issue.

**Comment by nicksnyder** [comment]
Thanks for reporting, this looks like a easy fix as you suggested.

**Comment by fgm** [comment]
Do you want a PR ?
