### ISSUE TITLE
Question: {{T "messageID" .Param1 .Param2}} in v2

### ISSUE THREAD

**Issue by zengabor** [nicksnyder/go-i18n#150]
Hi, just found this package today, played around with v2 a little bit, and it works great. Great package.

My goal is to use translations from `html/template` files only, like this:

    {{T "messageID" .Param1 .Param2}}

I see that there isn't a `Tfunc()` in v2 as opposed to v1 so I wrote a wrapper:

	lang := r.FormValue("lang")
	accept := r.Header.Get("Accept-Language")
	localizer := i18n.NewLocalizer(bundle, lang, accept)
	T := func(messageID string, args ...interface{}) string {
		lc := i18n.LocalizeConfig{MessageID: messageID}
		if len(args) > 1 {
			lc.PluralCount = args[0]
			td := make(map[string]interface{})
			td["PluralCount"] = lc.PluralCount
			for i := 1; i < len(args); i++ {
				td["P"+strconv.Itoa(i)] = args[i]
			}
			lc.TemplateData = td
		}
		return localizer.MustLocalize(&lc)
	}
	t.Funcs(map[string]interface{}{
		"T": T,
	})
	...

This makes it possbile to have a translation like this:

    [PersonUnreadEmails]
    description = "The number of unread emails a person has"
    one = "{{.P1}} has {{.PluralCount}} unread email."
    other = "{{.P1}} has {{.PluralCount}} unread emails."

So the first argument is always translated to `PluralCount` and the rest is numbered, like `P1`, `P2` and so on, and then I can use it like this:

	{{T "PersonUnreadEmails" .NumberOfUnreadEmail .PersonName}}

This works perfectly but is this also how you would do it? Is there a better way?

**Comment by zengabor** [comment]
Having real names instead of `P1`, `P2`, etc. is of course a huge benefit. So I ended up implementing it by taking the default language of the bundle as reference, and collecting the used names in the "Other" template.

In my first attempt I added this to your `localizer.go` file:

```go
// To be used in template FuncMap, like tmpl.Funcs(template.FuncMap{"T": localizer.T()})
func (l *Localizer) T() func(messageID string, args ...interface{}) (string, error) {
	return func(messageID string, args ...interface{}) (string, error) {
		lc := LocalizeConfig{MessageID: messageID}
		td := make(map[string]interface{})
		al := len(args)
		for i, n := range l.referenceArgNames(messageID) {
			if i >= al {
				break
			}
			td[n] = args[i]
			if n == "PluralCount" {
				lc.PluralCount = args[i]
			}
		}
		lc.TemplateData = td
		return l.Localize(&lc)
	}
}

var argMatcher = regexp.MustCompile(`{{\s?\.(\w+)\s?}}`)

// Collects the names of arguments in the "Other" template of the default language of the bundle
func (l *Localizer) referenceArgNames(id string) []string {
	var r []string
	tags := []language.Tag{l.bundle.DefaultLanguage}
	_, t := l.matchTemplate(id, nil, language.NewMatcher(tags), tags)
	for _, m := range argMatcher.FindAllStringSubmatch(t.PluralTemplates[plural.Other].Src, -1) {
		r = append(r, m[1])
	}
	return r
}
```

This works great. However, maybe the argument names could be already collected as soon as the bundle file for the default language is loaded. Then there is no need to look them up every time. I will refine it.

**Comment by nicksnyder** [comment]
Thanks for sharing your thoughts here! I haven't yet thought about the best way to do this in templates, but it seems like you are figuring it out :)

**Comment by zengabor** [comment]
Thank you! Will come back to you once I have a better proposal. :)

**Comment by liuggio** [comment]
Version 1 has a better dev experience, `Messages` are not really a standard way to use the translation, using templating with this module is not a rational experience.

**Comment by nicksnyder** [comment]
One of the goals of v2 is to make messages extractable. Defining messages in template files (or strings) makes this much more difficult.

It is certainly possible to define a `T` func as mentioned above if you are willing to give up extractability, but my recommendation is to localize messages in Go and then pass the localized messages as data to the template. This is demonstrated in the [example](https://sourcegraph.com/github.com/nicksnyder/go-i18n/-/blob/v2/example/main.go#L16:19).

> My goal is to use translations from html/template files only, like this:

@zengabor I am curious, why is this your goal? Is there something that prevents you from doing (or makes it undesirable to do) the localization in Go and passing the localized messages as data to the template?
 
If I were to implement a T function, I would probably make it look like this (untested):

```go
func (l *Localizer) T() func(messageID string, args ...interface{}) (string, error) {
	return func(messageID string, args ...interface{}) (string, error) {
		kv := map[string]interface{}{}
		key := ""
		for _, arg := range args {
			if key == "" {
				key, _ = arg.(string)
				if key == "" {
					return "", fmt.Errorf("expected string key but got %#v", arg)
				}
			} else {
				kv[key] = arg
				key = ""
			}
		}

		lc := &LocalizeConfig{
			MessageID:    messageID,
			PluralCount:  kv["PluralCount"],
			TemplateData: args,
		}

		return l.Localize(lc)
	}
}
```

**Comment by zengabor** [comment]
Hi Nick, I am having trouble understanding what the issue is. I would like to use (not define) translations like this:

  {{T "messageID" .Param1 .Param2}}

I am reusing the same templates in multiple places: to pre-render pages to static files as well as to dynamically serve content. So text are kept together with their presentation. The different Go codes that use the template can focus on passing data to the templates.

Why goes this against "extractability"? What do you mean by "extractable"? Why is it better to get the translations first then pass it to the template?

Thanks in advance.

**Comment by nicksnyder** [comment]
There isn't an issue per se; you can implement a T function as discussed above to achieve your goals, but you won't be able to use `goi18n extract` in its current form. If that isn't a concern for you, then go ahead!

> Why does this go against "extractability"? What do you mean by "extractable"?

One of the design goals of v2 was to make it possible to define source translations in Go files so that they can be automatically extracted to translation files (see https://github.com/nicksnyder/go-i18n/issues/64).

> Why is it better to get the translations first then pass it to the template?

This extraction depends on having a structured call site, which is much cleaner with Go syntax than Go template syntax (which is less expressive).

Template parameters are named, not ordered, so the call site would probably need to be `{{T "messageID", "key1", "value1", "key2", "value2"}}`

> I am reusing the same templates in multiple places: to pre-render pages to static files as well as to dynamically serve content. So texts are kept together with their presentation. The different Go codes that use the template can focus on passing data to the templates.

If you wanted this to work with `goi18n extract` you could create a single Go function to render each template. The multiple call sites would call this function instead of rendering the template directly, so that this function could appropriately.

I am not categorically opposed to adding T func support to v2, but it might be confusing if there are multiple workflows. It would be nice if the T func was as powerful as the Localize call site and also worked with `goi18n extract`, but I am not sure if there is a clean way to satisfy all those constraints.

**Comment by zengabor** [comment]
Thank you very much for the detailed explanation. I am going to spend more time to understand these concepts. Closing this issue for now.

**Comment by nicksnyder** [comment]
If after trying out the new way you think the old way is better let me know and we can think about this more.
