### ISSUE TITLE
Loading message from DB

### ISSUE THREAD

**Issue by mimol91** [nicksnyder/go-i18n#155]
Hey,
Is it possible to add some method to load message not from file, but from other sources (like redis). 
For each messageId I have separate redis key.
It is possible to set `unmarshalInterface` as public method? or load data from io.reader?

**Comment by nicksnyder** [comment]
Hmm, yes I intended this to be possible but maybe I didn't export enough to make this convenient.

Given the current API, you can either call [ParseMessageFileBytes](https://github.com/nicksnyder/go-i18n/blob/master/v2/i18n/bundle.go#L75) and give it a fake path that just contains the name and the format, you can construct Message and use [AddMessages](https://github.com/nicksnyder/go-i18n/blob/master/v2/i18n/bundle.go#L96).

Would exporting unmarshalInterface solve your problem?

**Comment by mimol91** [comment]
Yes, currently I am creating message by using `unmarshalInterface` (I've copied whole code) - I would rather want to avoid copying.

**Comment by nicksnyder** [comment]
I just looked at the code and I don't understand how exporting `unmarshalInterface` would help. Is it not sufficient to use [NewMessage](https://sourcegraph.com/github.com/nicksnyder/go-i18n/-/blob/v2/internal/message.go#L47:12), which calls `unmarshalInterface`?

**Comment by mimol91** [comment]
NewMessage is in internal package, Cant use it .
Would be great if you expose it in `go-i18n/v2/i18n/message.go`
