### ISSUE TITLE
Hebrew support

### ISSUE THREAD

**Issue by MarlikAlmighty** [nicksnyder/go-i18n#156]
Thanks for the work, I have a problem with Hebrew, writes this error:
panic: no language found in "hebrew.all.json"

**Comment by nicksnyder** [comment]
You need to use the ISO-2 language tag. Try `he.all.json`

https://en.m.wikipedia.org/wiki/Hebrew_language

**Comment by MarlikAlmighty** [comment]
Thank you, it works.
