### ISSUE TITLE
unknown field 'DefaultLanguage'

### ISSUE THREAD

**Issue by dinfyru** [nicksnyder/go-i18n#167]
bundle = &i18n.Bundle{DefaultLanguage: language.English}

./main.go:33:24: unknown field 'DefaultLanguage' in struct literal of type i18n.Bundle

**Comment by nicksnyder** [comment]
Sorry about that, I forgot to update the README after I made an API change yesterday.

**Comment by nicksnyder** [comment]
Use `i18n.NewBundle(language.English)` instead.
