### ISSUE TITLE
read translations from string?

### ISSUE THREAD

**Issue by cytec** [nicksnyder/go-i18n#18]
I would love to include my translated files with `go-bindata` thus not providing access to a file but a string/byte pointer of the file content.

Is there a way i can load translations from string or an `go-bindata` Asset?
see: https://github.com/jteeuwen/go-bindata

**Comment by nicksnyder** [comment]
Can you describe why you want to do this and/or the advantages of using go-bindata over the current approach of loading a JSON file at runtime?

**Comment by cytec** [comment]
because i think its simpler to distribute a single binary to the enduser then needing them to have a setup folder structure with JSON Files.

**Comment by nicksnyder** [comment]
I added ParseTranslationFileBytes, which should give you what you want. Reopen if that doesn't work for you.

**Comment by cytec** [comment]
works perfectly, thanks :)
