### ISSUE TITLE
Proper use of Go Module versioning?

### ISSUE THREAD

**Issue by vassudanagunta** [nicksnyder/go-i18n#180]
Why

```
require github.com/nicksnyder/go-i18n/v2
```

instead of

```
require github.com/nicksnyder/go-i18n v2.0.0
```

?

If you stick with the former, the future will look like this:

```
require github.com/nicksnyder/go-i18n/v2 v2.0.1
require github.com/nicksnyder/go-i18n/v2 v2.1.0
require github.com/nicksnyder/go-i18n/v2 v3.0.0
...
```

or this:

```
require github.com/nicksnyder/go-i18n/v2 v2.0.1
require github.com/nicksnyder/go-i18n/v2 v2.1.0
require github.com/nicksnyder/go-i18n/v3 v3.0.0
...
```

Now is the time to get this right! :wink:

**Comment by nicksnyder** [comment]
Can you clarify what you are asking me to change?

**Comment by nicksnyder** [comment]
v2 is not backward compatible with v1, which is why it has a different import path. See https://github.com/golang/go/wiki/Modules#semantic-import-versioning

> require github.com/nicksnyder/go-i18n/v2 v3.0.0

It would actually be `require github.com/nicksnyder/go-i18n/v3 v3.0.0` instead.

This is how Go modules work.

**Comment by vassudanagunta** [comment]
My bad. I had assumed Go Modules worked like NPM, where you are expected NOT to rename a module and simply rely on SemVer to express incompatibility. It does seem redundant and wrong, since  `require github.com/nicksnyder/go-i18n v1` already means "latest available tagged version with the prefix `v1`", i.e. not v2.

Even Russ Cox initially didn't like it:

> A year ago I strongly believed that whether to include version numbers in import paths was largely a matter of taste, and I was skeptical that having them was particularly elegant.

But he changed his mind, and there are good arguments for it, despite the redundancy. Sorry for wasting your time. But I learned something. 😝
