### ISSUE TITLE
When trying to translate with `zero` values, translation.*.toml file gets messed up

### ISSUE THREAD

**Issue by anatoliyfedorenko** [nicksnyder/go-i18n#197]
I have the following translation for my `active.en.toml`
```[internshipDuration]
few = "{{.Days}} on internship"
many = "{{.Days}} on internship"
one = "added yesterday"
other = "{{.Days}} on internship"
two = "2 days on internship"
zero = "added today"
```
When i do `goi18n merge active.*.toml translate.*.toml` my `translate.ru.toml` gets populated with 
```
[internshipDuration]
few = "{{.Days}} on internship"
hash = "sha1-9f6f71e74105fd8b940001ed3faa3ab50e5c015e"
many = "{{.Days}} on internship"
one = "{{.Days}} on internship"
other = "{{.Days}} on internship"
```
which I see as somewhat problematic, since I need to have `zero` as well and it is not there :( Plus the values are messed up, see value for `one` and hash is not at the top. 

So, if I have `zero` value translation, it breaks the generators. Any fixes on that?

**Comment by anatoliyfedorenko** [comment]
just understood that this is also not working even without `zero` value :( 
Trying to get translation for the following message: 
```
internshipDuration, err := localizer.Localize(&i18n.LocalizeConfig{
			DefaultMessage: &i18n.Message{
				ID:    "internshipDuration",
				One:   "{{.Days}} day on intership",
				Two:   "{{.Days}} days on internship",
				Few:   "{{.Days}} days on internship",
				Many:  "{{.Days}} days on internship",
				Other: "{{.Days}} days on internship",
			},
			PluralCount: int(daysOnInternship),
			TemplateData: map[string]interface{}{
				"Days": int(daysOnInternship),
			},
		})
```

**Comment by nicksnyder** [comment]
>  I need to have zero as well and it is not there :(

Russian does not have a CLDR plural form for zero, it only has "one", "few", "many", "other".

If you want a special translation for when a value is `0` then you need to have a separate message for that and do the switch in code.

> Plus the values are messed up, see value for one and hash is not at the top.

The order doesn't matter, it is just a hash map.
