### ISSUE TITLE
Has the JSON file name convention changed?

### ISSUE THREAD

**Issue by Waitak** [nicksnyder/go-i18n#198]
I've just moved to the current version. Bundle.LoadMessageFile appears to be interpreting "de.all.json" as though "all" is the language tag, and failing because there are no pluralization rules available for "all". It appears to be expecting "de.json" instead of "de.all.json". The goi18n command, though, is creating *.all.json just as before. What's going on here?

**Comment by Waitak** [comment]
The file name did indeed change. Is there a document that describes how to move from version 1 to version 2 that I could have read to help me over these issues?

**Comment by nicksnyder** [comment]
Sorry for the rough transition. This is as close as I got to a migration guide: https://github.com/nicksnyder/go-i18n/blob/master/CHANGELOG.md#changelog

v2 is essentially a new library.
