### ISSUE TITLE
Proposal: make a section in README.md file, with examples of programs that use the library

### ISSUE THREAD

**Issue by d2r2** [nicksnyder/go-i18n#199]
@nicksnyder, can I ask you to make a section in README.md file, with examples of programs that use your library? Honestly, I would like to propose a link to my helpful desktop application written in Golang with localization made with your library: [https://github.com/d2r2/go-rsync](https://github.com/d2r2/go-rsync).
P.S. I can propose this change, If you don't mind.

**Comment by nicksnyder** [comment]
I don't think I would want to add a section like this to the readme. If you think the current examples/documentation in the project are lacking then I would rather focus on improving those directly.
