### ISSUE TITLE
Is MustLoadLanguageFile / LoadLanguageFile a stickler for paths?

### ISSUE THREAD

**Issue by Parul4singh** [nicksnyder/go-i18n#200]
I am using go-i18n to localize dexidp app. Specifying my path as absolute in MustLoadLanguageFile / LoadLanguageFile breaks the build. 
My locales folder path - locales/en-US.toml
My current file path - localize/translate/translate.go

I use 
lang = "en-US"
messageFileToLoad := fmt.Sprintf("locales/%s.toml", lang)
	_, e := bundle.LoadMessageFile(messageFileToLoad)
which seems to work great locally but I get a build erros:-
Failed loading message file:  open locales/en-US.toml: no such file or directory

Please help

**Comment by nicksnyder** [comment]
If you are using a relative path, the path needs to be relative to your final binary. Unfortunately there isn't enough information in your issue description for me to help you further.

**Comment by Parul4singh** [comment]
> If you are using a relative path, the path needs to be relative to your final binary. Unfortunately there isn't enough information in your issue description for me to help you further.

I am getting error with path even if I have my en-US.toml file in the same directory. I get open ./en-US.toml: no such file or directory

**Comment by dalu** [comment]
I was about to open a similar issue.
This library should support loading by [io.Reader](https://golang.org/pkg/io/#Reader)
Since one usually ... well shouldn't use the os' filesystem directly but eventually embed files into the binary, adding a `LoadMessageByReader(reader io.Reader, path string ) (*Message, error)` would add a good convenience method.

**Comment by nicksnyder** [comment]
ParseMessageFileBytes already exists, so you can use that directly. You can use [ioutil.ReadAll](https://golang.org/pkg/io/ioutil/#ReadAll) to first convert your `io.Reader` to a `[]byte`. Feel free to open a PR to add ParseMessageFileReader which accepts a reader, and does what I said above.

**Comment by danielcherubini** [comment]
There is something in here that is perhaps more of a separate issue, but the way @Parul4singh was loading the files was more of a "load all the files from this folder"..

I was wondering if you would perhaps be interested in a `loadMessagesFolder` function that would take a path, iterate over the files in the folder and load them.. perhaps taking two params, the first being the folder path, and the second to be the file extension, something like;

`func (b *Bundle) LoadMessageFolder(path string, extension string) (*MessageFile, error)`
