### ISSUE TITLE
The JSON version of examples

### ISSUE THREAD

**Issue by dalu** [nicksnyder/go-i18n#204]
There are TOML examples.

What is the JSON format structure of v2, please?
Has it changed from v1?

**Comment by dalu** [comment]
Actually never mind, I had a multi-line string and didn't know how to write one in toml.

```
"""This
is
a
multi-line
string"""
```

I have another question though, if I have only one definition, in my cast I'm trying to provide translation for complete email templates, do I define one or just other or is there a default type definition?

**Comment by nicksnyder** [comment]
can you give an example for your second question?

**Comment by dalu** [comment]
It's all good.
It's answered here: https://github.com/nicksnyder/go-i18n/blob/master/v2/i18n/example_test.go#L73

Other is essentially a generic version of a text.

Let's say I have
```toml
[AccountActivation]
description = "account activation email"
other = """\
Dear {{ .Email }},

your account was created. In order to use the full functionality you need to verify your email address.
Please click the following link to verify your account:

https://{{ .Domain }}/account/manage/verify_email?code={{ .Code }}

Best regards,
"""

[AccountReset]
description = "account reset email"
other = """
Dear {{ .Email }},

you have requested a password reset.
Please click the following link to reset your password:

https://{{ .Domain }}/account/manage/reset_password?email={{ .Email }}&code={{ .Code }}

Best regards,
"""
```

`Other`: is the default type
