### ISSUE TITLE
Help Using Funcs

### ISSUE THREAD

**Issue by jamesgoodhouse** [nicksnyder/go-i18n#206]
I have setup a `LocalizeConfig` to include a `Funcs` definition. However, it's unclear how those are to be used. When I attempt to use a function I've defined in a template, I get a panic saying it is not defined.

Is there additional documentation on how one uses these?

**Comment by nicksnyder** [comment]
There isn't any additional documentation right now. The `Funcs` you provide are forwarded to [.Funcs](https://godoc.org/text/template#Template.Funcs) on `text/template` [here](https://sourcegraph.com/github.com/nicksnyder/go-i18n@26334ab1db070c2801ba26550d7d6238f6c9da10/-/blob/v2/internal/template.go#L40:13). It is definitely possible there is a bug; I just realized there are no unit tests to cover this. If you are seeing a panic can you post a stack trace?

**Comment by patgrasso** [comment]
@nicksnyder I've also encountered a panic when running `goi18n extract` with `Funcs` provided. I haven't delved too deep into _why_ it happens, but it appears to stem from [this line in `extractStringLiteral()`](https://github.com/nicksnyder/go-i18n/blob/275c8ecd2b9eb2da0b5efae46e8f3b01c5e5261c/v2/goi18n/extract_command.go#L262). An instance of `*ast.Ident`'s `Obj` field is used without a nil pointer check.

Here's a simple case that triggers the problem.
```go
// funcs.go
package bug

import "text/template"

var Funcs = template.FuncMap{
	"noop": func(x interface{}) interface{} {
		return x
	},
}
```
```go
// render.go
package bug

import "github.com/nicksnyder/go-i18n/v2/i18n"

func Render(m *i18n.Message) {
	l := i18n.NewLocalizer(nil, "en")
	l.Localize(&i18n.LocalizeConfig{
		DefaultMessage: m,
		Funcs: Funcs,        // <- note, Funcs is define in another file
	})
}
```

However, it works just fine if I define `Funcs` in the same file as where it's used.
```go
// render.go
package bug

import (
	"github.com/nicksnyder/go-i18n/v2/i18n"
	"text/template"
)

var Funcs = template.FuncMap{
	"noop": func(x interface{}) interface{} {
		return x
	},
}

func Render(m *i18n.Message) {
	l := i18n.NewLocalizer(nil, "en")
	l.Localize(&i18n.LocalizeConfig{
		DefaultMessage: m,
		Funcs: Funcs,
	})
}
```

It seems like a reasonable solution might be to just return from `extractStringLiteral` if the identifier's `Obj` is nil.

Would be happy to open a PR with a fix & a corresponding test case if you agree!

**Comment by patgrasso** [comment]
Also, I'm not 100% sure if this problem is the same as the one jamesgoodhouse is seeing, so if you want me to open a separate issue for this let me know.

**Comment by nicksnyder** [comment]
@patgrasso Looks like you found a bug, thanks! Yes please open a PR if you can to fix this (and include tests).
