### ISSUE TITLE
Bulk translation for huge html page

### ISSUE THREAD

**Issue by johndark** [nicksnyder/go-i18n#214]
Hello.

Thanks for the nice package. I use it already in the third project, and now there is a huge amount of translation for big HTML templates. Until now, I used .toml with a fairly simple structure, for example:
```
text1 = "something for text1"
text2 = "something for text2"
```
and used it like:
```
return localizer.MustLocalize(&i18n.LocalizeConfig{
    DefaultMessage: &i18n.Message{
        ID: id,
    },
})
```
But now, I have big HTML files with a lot of text to translate inside (like name of buttons, fields, labels, note text, alerts and etc.) and If I'll use the same algo, it will be infinitely long pieces of code listing each ID. Can I somehow load part of the IDs from the language file into the map. For example, all IDs starting with the suffix `common-`? Or all IDs under [area]?

PS: Sorry, I'm new in golang.

**Comment by nicksnyder** [comment]
> Can I somehow load part of the IDs from the language file into the map. For example, all IDs starting with the suffix common-? Or all IDs under [area]?

This is not supported directly in this library, but you could write your own function to do just that.

**Comment by johndark** [comment]
> This is not supported directly in this library, but you could write your own function to do just that.
Thank you for reply. Yeah, I'll do so.

**Comment by CarsonSlovoka** [comment]
DefaultMessage is not necessary, make sure you load <sup>[LoadMessageFile]</sup> all language (include [default](https://github.com/nicksnyder/go-i18n/blob/66dee750b54fda381116a1c93336f24f67b2613f/v2/example/main.go#L30))

and then, only provide [MessageID].

[LoadMessageFile]: https://github.com/nicksnyder/go-i18n/blob/66dee750b54fda381116a1c93336f24f67b2613f/v2/i18n/bundle.go#L54

[MessageID]: https://github.com/nicksnyder/go-i18n/blob/66dee750b54fda381116a1c93336f24f67b2613f/v2/i18n/localizer.go#L45-L47
