### ISSUE TITLE
Automatic translation support

### ISSUE THREAD

**Issue by braderhart** [nicksnyder/go-i18n#215]
Hello, I was wondering if you have considered adding automatic translation support as an option? Here is some links with code examples if you may be up for the task of adding more options:

- https://www.soimort.org/translate-shell
- https://toolkit.translatehouse.org

This would be ideal for Hugo to automatically generate translations.

**Comment by nicksnyder** [comment]
If anyone creates a tool that can automatically translate messages using the file format that go-i18n supports, then I would be happy to link to such a tool from the readme, but this is not within scope for the library itself.
