### ISSUE TITLE
Get raw message string from loaded json files

### ISSUE THREAD

**Issue by mdost** [nicksnyder/go-i18n#218]
Is there anyway to get raw text from the files?
I'm loading in the json files and I want to get the original string as reference (unaltered string)
For example in my json file:
```
{
        "id": {
            "description": "test description",
            "other": "Failed to delete {{.filename}}"
        }
    }
```
What I want is to get this string `Failed to delete {{.filename}}`
So in my code:
```
loc := i18n.NewLocalizer(i18nBundle, "en")
translatedMessage, err := loc.Localize(&i18n.LocalizeConfig{
	MessageID:    msgId,
	TemplateData: nil,
})
```
If data is nil, then the output is: `Failed to delete <no value>`. Which is not what i'm looking for.
Is there any way to do this using this library?

**Comment by nicksnyder** [comment]
The library does not currently support this. If you are looking for the raw data you could open and parse the json file yourself. What is your use case?
