### ISSUE TITLE
Memory usage when generating translations

### ISSUE THREAD

**Issue by zaddok** [nicksnyder/go-i18n#222]
Hi,

We are looking at implementing this for our rather large web application. Just learning how it works. It appears that to do a localisation of a string, there are three objects created in memory just to construct the call to the localisation function. It feels like we might be doing it wrong. Is this example Println statement below the correct way to ask for a localised string? Is there a simpler way?  

```
func main() {
	bundle := i18n.NewBundle(language.English)

	bundle.AddMessages(language.English,
		&i18n.Message{ID: "hello", Other: "hello y'all"},
	)
	bundle.AddMessages(language.BritishEnglish,
		&i18n.Message{ID: "hello", Other: "hello mate"},
	)
	bundle.AddMessages(language.Chinese,
		&i18n.Message{ID: "hello", Other: "你好"},
	)

	loc := i18n.NewLocalizer(bundle, "zh_CN")
	fmt.Println(loc.MustLocalize(&i18n.LocalizeConfig{DefaultMessage: &i18n.Message{ID: "hello"}}))

}
```

**Comment by nicksnyder** [comment]
`i18n.NewBundle`, and `bundle.AddMessages` are all one-time setup costs when your web app starts.

You should only need to call `i18n.NewLocalizer` once per request assuming that you are passing in a client provided user-agent string. If you have a fixed list of strings that you would pass in as the second argument to `NewLocalizer` then you could cache or pre-generate all localizers.

If you do not wish to provide a default message (which allows you to automatically extract translations from your app), then you can do this instead:

`loc.MustLocalize(&i18n.LocalizeConfig{MessageID: "hello"})`

**Comment by zaddok** [comment]
Wow that is an amazingly fast reply. Thanks for your work on this library. 

Yea, I am not talking about the setup at the start, I am talking about the way localisation is invoked:

	fmt.Println(loc.MustLocalize(&i18n.LocalizeConfig{DefaultMessage: &i18n.Message{ID: "hello"}}))

But now that I have had time to browse the source it creates a lot more objects under the hood as well. So it's probably not worth focussing on in light of what's going on underneath.

(We have an app that has a high number of requests per second and reducing object creation/cleanup helps keep our response time down. I know this is not a concern of most typical apps.)
