### ISSUE TITLE
Australian English

### ISSUE THREAD

**Issue by zaddok** [nicksnyder/go-i18n#223]
I imagine there are so many local variants of languages  in the world it would be hard for the language package to somehow specify all of them. However I am in a situation where we need to clearly delineate between US, UK, and Australian customers   (generally speaking Australian English is like UK English, but there are a more and more US influences which I need to accommodate for).

Is it possible to cater for regional variants? I actually think (given Australia is a country in and of itself), the language library should actually have en-au as an option, but it appears it does not, and I have not yet worked out how to request a change to that library.

**Comment by nicksnyder** [comment]
yes, this is possible. This library uses https://pkg.go.dev/golang.org/x/text@v0.3.3/language which supports any language.

For example, you can use `language.MustParse("en-AU")` for Australian English.
