### ISSUE TITLE
Safe extract locales with new lines (\n)

### ISSUE THREAD

**Issue by xTCry** [nicksnyder/go-i18n#233]
If the string has a newline character, a second slash is added during extraction `\\n`
This harms the final result of the translation

From 
```go
&i18n.Message{
	ID:    "ANY_MESSAGE",
	Other: "\nbar bar `{{.Prefix}} bar` bar bar bar!**\n\nfoo foo",
}
```
To
```toml
"ANY_MESSAGE" = "\\nbar bar `{{.Prefix}} bar` bar bar bar!**\\n\\nfoo foo"
```

How do I fix this so that a second slash isn't added every time?

**Comment by nicksnyder** [comment]
Thanks for reporting! This should be fixed in v2.1.2
