### ISSUE TITLE
Reading lang file embedded

### ISSUE THREAD

**Issue by oxodao** [nicksnyder/go-i18n#240]
Hi,

I can't use this library because it reads the translations straight from a path.

My goal is to use pkger to embed them in the binary.

Is there any plan to do a LoadMessageFile function that could work with pkger or any other embedding library ?

Thanks!

**Comment by nicksnyder** [comment]
You can use [ParseMessageFileBytes](https://sourcegraph.com/github.com/nicksnyder/go-i18n@main/-/blob/v2/i18n/bundle.go#L75:18)

**Comment by CarsonSlovoka** [comment]
I create an example for someone reference. <sup>need golang >= 1.16</sup>
> https://github.com/CarsonSlovoka/go-i18n/commit/78d7b32d5441278718d74624fac7960462beb625#diff-ea44924dd86a9031c26b5740aa0077920e8336cde15d06d04a37c51ee6a57363R12-R47

**Comment by nicksnyder** [comment]
Btw, you can now use [LoadMessageFileFS](https://sourcegraph.com/github.com/nicksnyder/go-i18n@main/-/blob/v2/i18n/bundlefs.go#L11)
