### ISSUE TITLE
Upgrade to go1.16 (for the embed)

### ISSUE THREAD

**Issue by CarsonSlovoka** [nicksnyder/go-i18n#255]
Hi, @nicksnyder 

This is a great project with comprehensive considerations, especially the function [ParseMessageFileBytes](https://github.com/nicksnyder/go-i18n/blob/66dee75/v2/i18n/bundle.go#L75) so that it can be combined with [embed](https://blog.carlmjohnson.net/post/2021/how-to-use-go-embed/) very quickly.

## question 

I want this project to support the ``embed`` package by default, and this must be a package allowed by [go1.16].

But the current project is stuck on [go1.9]. I think many versions have fallen behind the mainstream. Can you upgrade to go 1.16?

I am currently planning to write some `embed` examples <sup>for issue #240</sup> (I will announce later). I changed it to go1.16, everything is fine, and there seems to be no compatibility problem.

[go1.9]: https://github.com/nicksnyder/go-i18n/blob/cba41a4/v2/go.mod#L3
[go1.16]: https://blog.golang.org/go1.16

**Comment by nicksnyder** [comment]
What error message are you seeing when you try to use this package with go1.16?

Btw, you can now use [LoadMessageFileFS](https://sourcegraph.com/github.com/nicksnyder/go-i18n@main/-/blob/v2/i18n/bundlefs.go#L11)
