### ISSUE TITLE
go 1.16 - test failure in TestExecute/hello_{{

### ISSUE THREAD

**Issue by dbungert** [nicksnyder/go-i18n#259]
Greetings!

When running tests with go 1.16, the tests fail as follows
```
=== RUN   TestExecute/hello_{{
    template_test.go:57: expected err "template: :1: unexpected unclosed action in command"; got "template: :1: unclosed action"
--- FAIL: TestExecute (0.00s)
```

Retesting with go 1.15 results in passing tests.
Looks like the exact error strings has changed.

**Comment by nicksnyder** [comment]
Fixed by https://github.com/nicksnyder/go-i18n/pull/260
