### ISSUE TITLE
Zero value shows 's' in example program

### ISSUE THREAD

**Issue by opriz** [nicksnyder/go-i18n#263]
I run the example with unreadEmailCount=0 (http://localhost:8080/?unreadEmailCount=0),
the text is:
```
Hello Bob
I have 0 unread emails.

Bob has 0 unread emails.
```
Is it expected to show 's' by the end of 'email' when not further configured?

**Comment by nicksnyder** [comment]
Yes, zero is plural in English.

“I have 0 unread email” would be wrong English
