### ISSUE TITLE
Specifying the Tone (formal versus informal)

### ISSUE THREAD

**Issue by Dynom** [nicksnyder/go-i18n#265]
Hi,

Mostly a question I think, but what would be the best approach to offer a formal and an informal variant of a given translation? Fluent recommends using the Tone, but I think this is a custom extension.
```fluent
key = { TONE() ->
        [formal] ...
       *[informal] ...
    }
```

https://github.com/projectfluent/fluent/issues/300

**Comment by nicksnyder** [comment]
go-i18n doesn’t have any special handling for this so you would just treat these as two separate messages with two separate message ids.

```go

localizer.Localize(&i18n.LocalizeConfig{
    DefaultMessage: &i18n.Message{
        ID: "HelloFormal",
        Other: "Hello",
    },
})

localizer.Localize(&i18n.LocalizeConfig{
    DefaultMessage: &i18n.Message{
        ID: "HelloInformal",
        Other: "Hi",
    },
})
```
