### ISSUE TITLE
Dependency text 0.3.3 is vulnerable

### ISSUE THREAD

**Issue by Akaame** [nicksnyder/go-i18n#267]
As per https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXTEXTINTERNALLANGUAGE-2400718,

Dependency `golang.org/x/text` versions below `0.3.7` are vulnerable. Can we update to the latest version of this dependency? 

Cheers.

**Comment by nicksnyder** [comment]
Yep! Want to submit a PR?
