### ISSUE TITLE
go get -u "github.com/nicksnyder/go-i18n/v2/i18n"  # cd /root/go/GOCODE/src/github.com/nicksnyder/go-i18n; git pull --ff-only

### ISSUE THREAD

**Issue by passerbyo** [nicksnyder/go-i18n#278]
# go get -u "github.com/nicksnyder/go-i18n/v2/i18n" 
# cd /root/go/GOCODE/src/github.com/nicksnyder/go-i18n; git pull --ff-only
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

package github.com/nicksnyder/go-i18n/v2/i18n: exit status 1

**Comment by nicksnyder** [comment]
I am not sure what you are trying to do here so I don't know how to help.

To use go-i18n all you need to do is import the package in your go code
```
import "github.com/nicksnyder/go-i18n/v2/i18n"
```

If you are using go modules you should see an entry like this in your go.mod

```
github.com/gohugoio/go-i18n/v2 v2.2.0
```
