### ISSUE TITLE
How to generate translations for the toml files

### ISSUE THREAD

**Issue by sujatapatnaik52** [nicksnyder/go-i18n#283]
Hi, I was looking at the examples. One thing I am missing is - How to exactly translate all the messages in the translate.*.toml files? For po files there are some tools like poedit. Similary do they exist for json or toml files?

**Comment by nicksnyder** [comment]
I am not aware of similar tools. I would just edit the files directly like text files.

**Comment by sujatapatnaik52** [comment]
Like you need to be aware of that language to manually edit it. Isn't it?

**Comment by nicksnyder** [comment]
poedit just helps you edit the translation files, it doesn't do the translation for you afaik.

You need to get the messages translated either by human experts or in some automated way. go-i18n doesn't do either of these for you.
