### ISSUE TITLE
Cound you export this function or when translation has error get the original value

### ISSUE THREAD

**Issue by kumfo** [nicksnyder/go-i18n#289]
code:
https://github.com/nicksnyder/go-i18n/blob/639caa7eb5031c3fc275d5b3bf1f44fe3c3f2623/v2/i18n/localizer.go#L181

repeat issue:
https://github.com/nicksnyder/go-i18n/issues/275#issuecomment-1179462892

language.yaml:

```yaml
base:
  foo: "foo {{ bar }} "
```

when I want to translate `base.foo`, it will be get error tips: function "bar" not defined.
I wish the key `base.foo` is exists, I'll get the string value `foo {{ bar }}` for translate result，and the err tip. if the key is not exists, I'll get the err and empty result.

**Comment by nicksnyder** [comment]
If you set the `Funcs` field of `LocalizeConfig` then go-i18n can execute the template correctly: https://github.com/nicksnyder/go-i18n/blob/main/v2/i18n/localizer.go#L70

Does that solve your problem?

**Comment by kumfo** [comment]
> If you set the `Funcs` field of `LocalizeConfig` then go-i18n can execute the template correctly: https://github.com/nicksnyder/go-i18n/blob/main/v2/i18n/localizer.go#L70
> 
> Does that solve your problem?

Sorry, I don't want to implement the `Funcs`, but I just want to cooperate with the frontend for international template rendering.

**Comment by nicksnyder** [comment]
What are you going to do with the  "foo {{ bar }} " template once you have it?

**Comment by kumfo** [comment]
> What are you going to do with the "foo {{ bar }} " template once you have it?

frontend render the template like this: `{{ number }} years ago`, it can be rendered `10 years ago`.
but now I have to use golang to render the template consistent with the frontend, because I need adapt to the adjustment of SEO.

**Comment by kumfo** [comment]
I think that if can't parse functions  should be returned the original result more reasonable.

of course, the error message is also returned, in this way, I can handle the translated strings according to my own ideas.

**Comment by nohajc** [comment]
I have a similar problem and I've submitted a PR https://github.com/nicksnyder/go-i18n/pull/316 which makes it possible to just disable template processing completely.

I think it would make the library much more flexible in many real-world scenarios.

**Comment by nicksnyder** [comment]
With 2.4.0 there is now a way to disable template parsing. Check out the [release notes](https://github.com/nicksnyder/go-i18n/releases/tag/v2.4.0) for more info.
