### ISSUE TITLE
Hook to commonly catch errors

### ISSUE THREAD

**Issue by gokatz** [nicksnyder/go-i18n#290]
hey. First of all, Thanks for maintaining this library which helped me localize go serviceseaily.

I'm using this lib in couple of instances. I want to track all the missing translation (MessageNotFound) error for future reporting and fixes. I searched through the docs and cannot find a `onError` kinda hook something similar to [react-intl's onError hook](https://formatjs.io/docs/react-intl/components/#onerror). Is there any recommendations on this? I would be happy to build one :) Thanks

**Comment by nicksnyder** [comment]
"Which messages are missing translations" is a question that seems best answered offline. In fact, the `goi18n` command has a workflow that generates a file for you with all missing translations so you can go get them translated. Docs here: https://drive.google.com/drive/u/0/folders/1PUq6vyp8vsAHdmu_qsE6sP3VtoIcWLzL

Does that solve your problem?

**Comment by gokatz** [comment]
Hey, @nicksnyder thanks for the response. Requested access :) 

>Which messages are missing translations
For my use case, messages / IDs for which translation are not available in the translated json file. We try to have 0 English messages in app when the user choose a Non English version. We'll use this hook (or something similar) to audit and fix the issues.

**Comment by gokatz** [comment]
> correct, but goi18n can produce a file that contains all missing translations (this doesn’t need to happen at runtime)

Thanks. I didn't know that. Any documentation on would be great :) 

That said, we need runtime analysis, because, runtime provides more weighted analysis. For instance, 
- particular message might not be translated at all. At the same time, that message has nearly zero traffic. In that case, that missing translation issue has less priority vs a missing translation that has huge traffic.
- there might be missing translations for a message behind a flag. That code path will never be executed until we flip the flag. Until then, this missing translation has not priority at all.

We are building system based on these priorities. Any suggestions would be great :)

**Comment by nicksnyder** [comment]
I would recommend creating your own wrapper Localizer type that contains a i18n.Localizer and forwards methods to it. Then you can implement whatever hook you want when there is an error.

```go

type Localizer struct {
	// bundle contains the messages that can be returned by the Localizer.
	l *i18n.Localizer
}

func (l *Localizer) LocalizeWithTag(lc *i18n.LocalizeConfig) (string, language.Tag, error) {
	msg, tag, err := l.LocalizeWithTag(lc)
	if mnfErr, ok := err.(*i18n.MessageNotFoundErr); !ok {
		// do whatever you want, this is your hook
	}
	return msg, tag, err
}
```
