### ISSUE TITLE
Upgrade golang.org/x/text

### ISSUE THREAD

**Issue by mr-nick17** [nicksnyder/go-i18n#301]
Current version of go-i18n uses `golang.org/x/text@v0.4.0`, which has a vulnerability (https://pkg.go.dev/vuln/GO-2023-1988) in versions < v0.13.0

```
github.com/nicksnyder/go-i18n/v2@v2.2.1 requires
golang.org/x/text@v0.4.0 requires
golang.org/x/tools@v0.1.12 requires
golang.org/x/net@v0.0.0-20220722155237-a158d28d115b
```

**Comment by nicksnyder** [comment]
Thanks for the report. To unblock your project, you can always require a newer version of this dependency in your own go.mod.
