### ISSUE TITLE
Breaks on key description

### ISSUE THREAD

**Issue by mateors** [nicksnyder/go-i18n#302]
It breaks when I add the following in my language file

```
{
...
    "description": "Description"
...
}
```

**Comment by nicksnyder** [comment]
Correct, “description” is one of the reserved words that you can’t use as a message id.

Here are all words you can’t use:
https://github.com/nicksnyder/go-i18n/blob/381afe6807f01999bbbcfbc24d67d2bb61221bd9/v2/i18n/message.go#L72-L92
