### ISSUE TITLE
Expose fields (or add access methods) of MessageNotFoundErr

### ISSUE THREAD

**Issue by stephenafamo** [nicksnyder/go-i18n#306]
With `errors.As`, it is now possible to detect the error, but since the fields are private, there is no way to extract the structured details without resorting to string parsing.

**Comment by nicksnyder** [comment]
What is your use case for wanting access to the underlying fields?

**Comment by stephenafamo** [comment]
For now, I am doing structured logging and would prefer to have the language and message key as fields.

In the future, I intend to send custom alerts to ease the translation flow.

**Comment by stephenafamo** [comment]
Any intention of exposing this? 🙏🏾

**Comment by nicksnyder** [comment]
I don't have a strong objection. If you want to open a PR I will review it.
