### ISSUE TITLE
Support template.Options for setting up missing key behavior

### ISSUE THREAD

**Issue by demsasha4yt** [nicksnyder/go-i18n#315]
Currently, there is no support to parse and execute templates with missing key options. https://github.com/nicksnyder/go-i18n/blob/main/v2/internal/template.go#L36C28-L36C28

As a result, it is not possible to return error if any variable is missing in render payload 

Kindly consider supporting text/template options https://pkg.go.dev/text/template#Template.Option

> "missingkey=default" or "missingkey=invalid"
> 	The default behavior: Do nothing and continue execution.
> 	If printed, the result of the index operation is the string
> 	"<no value>".
> "missingkey=zero"
> 	The operation returns the zero value for the map type's element.
> "missingkey=error"
> 	Execution stops immediately with an error.

**Comment by nicksnyder** [comment]
Seems reasonable. If you want to open a PR I would review it.

**Comment by nicksnyder** [comment]
With 2.4.0 there is now a way to specify a `Template.Option`. Check out the [release notes](https://github.com/nicksnyder/go-i18n/releases/tag/v2.4.0) for more info.
