### ISSUE TITLE
Can we add support of Tajik (TG) language

### ISSUE THREAD

**Issue by Djutifai** [nicksnyder/go-i18n#321]
Getting the `no plural rule registered for tg` error. Did not find Tajik language in Plural Rules gen

**Comment by nicksnyder** [comment]
go-i18n depends on https://github.com/unicode-org/cldr for language support and rules. To add support for a new language, get it added there and then go-i18n can update to the latest data.

**Comment by Djutifai** [comment]
If im not mistaken, [it is already added there](https://st.unicode.org/cldr-apps/v#/tg_TJ//). 
Can't this be fixed [in i18n here](https://github.com/nicksnyder/go-i18n/blob/main/internal/plural/rule_gen.go)?
On [this line](https://github.com/nicksnyder/go-i18n/blob/7c6508d75732c7b2b41bc9f46ce9e9a3c7fefff4/internal/plural/rule_gen.go#L78), for example
