### ISSUE TITLE
Errors out when the starting curly brace coincides with a variable

### ISSUE THREAD

**Issue by adarsh1001** [nicksnyder/go-i18n#333]
So I have a message of this form "Hi, my name is {{{.Name}}. Nice to meet you!}".

{{.Name}} is a variable of course, and the extra {} wrapping around it is needed as it is in the string. So the expected output is: "Hi, my name is {Adarsh. Nice to meet you!}". Instead, this throws an error `unexpected \"{\" in command`. The curly braces work as long as the starting curly brace doesn't have the variable curly brace next to it. So something like this works: "Hi, my name {is {{.Name}}}. Nice to meet you!".

**Comment by nicksnyder** [comment]
You can add a space and the trim it out:

"Hi, my name is { {{- .Name}}. Nice to meet you!}".

docs: https://pkg.go.dev/text/template#hdr-Text_and_spaces

Alternatively you can set a TemplateParser on your LocalizeConfig and use custom delimiters.
https://github.com/nicksnyder/go-i18n/blob/8f901dbb359899fb721f5091dfc7f344a5fba578/i18n/localizer.go#L75
