### ISSUE TITLE
Text decoration not possible

### ISSUE THREAD

**Issue by yanngit** [nicksnyder/go-i18n#353]
Hello,
I'm trying to add a text decoration in my translation but it seems not to be working ... 
Do you have any clue on how can i add a 'strong' in the middle of my translated sentence ? 
Thanks

**Comment by nicksnyder** [comment]
Not sure what you mean, but whatever you are trying to accomplish, you would do it in the exact same way as you would if you weren’t using go-18n.

**Comment by yanngit** [comment]
It was a templ related issue, will close this :) thanks !
