### ISSUE TITLE
cannot find package "gopkg.in/yaml.v2"

### ISSUE THREAD

**Issue by dougbeauchene** [nicksnyder/go-i18n#42]
Please forgive my question as I'm somewhat new to Golang.

A recent change in  go-i18n/i18n/bundle/bundle.go  to import  gopkg.in/yaml.v2  started causing my build to fail with this error....

src/github.com/nicksnyder/go-i18n/i18n/bundle/bundle.go:7:2: cannot find package "gopkg.in/yaml.v2"

I use "git clone" to pull down all depend projects so I'm not sure if I can only get the package above via "go get" or if there should be a github repo with the changes that I can clone from.

**Comment by nicksnyder** [comment]
I think you will need to `go get` gopkg.in/yaml.v2. Please let me know if that doesn't work.

**Comment by dougbeauchene** [comment]
Nick, 

I tried adding     go get gopkg.in/yaml.v2     and it does resolve the issue.  Was just wondering why.  I did find this   https://github.com/spf13/hugo/issues/297    that talks a little about gopkg.in being version aware.

Thanks for the quick reply.

**Comment by nicksnyder** [comment]
@dougbeauchene Thanks for reminding me that this requires an extra step now. I will update the README.
