### ISSUE TITLE
 Two simple features request

### ISSUE THREAD

**Issue by Alexeyco** [nicksnyder/go-i18n#43]
__CLDR `zero` key support__

````json
[
  {
    "id": "{{.Count}} users online",
    "translation": {
      "zero": "Никого нет",
      "other": "{{.Count}} пользователей онлайн"
    }
  }
]
````

__Random translations__

The idea is to be able to return a random phrase, if the term translation is an array

````json
[
  {
    "id": "Hello",
    "translation": ["Привет", "Здарова", "Привет, братюня", "Как сам?"]
  }
]
````
...or so...

````json
[
  {
    "id": "{{.Count}} apples",
    "translation": {
      "one": "{{.Person}} яблоко",
      "other": ["{{.Count}} яблок", "{{.Count}} яблочек"]
    }
  }
]
````

**Comment by nicksnyder** [comment]
In the future, please open a separate issue for each idea.

The zero cldr category is already supported so I don't understand what you are asking for. Can you clarify?

Randomness doesn't belong in this library. Give each string a unique id and do the random selection in your own app code.
