### ISSUE TITLE
How do you handle l10n ?

### ISSUE THREAD

**Issue by abourget** [nicksnyder/go-i18n#45]
How do you handle the format for dates, numbers, etc.. ?

How about stealing this: https://github.com/jbnicolai/closure-library/blob/20702eff5afe0fd9d8c5a42254879fc18c34253b/closure/goog/i18n/datetimepatternsext.js ?

For example, the angular folks leverage it through their https://docs.angularjs.org/api/ng/filter/date filter.. same with number and currency filters..

**Comment by nicksnyder** [comment]
This library does not currently handle date and number formatting. If we added support, I ideally would want to generate the code from the CLDR data much like we do for plural configuration.

**Comment by abourget** [comment]
CLDR data has all of that ?  I don't know much about CLDR but I might be
willing to take a bite at it. Do you have references ?

**Comment by nicksnyder** [comment]
Number formatting:
http://cldr.unicode.org/translation/number-patterns

Date formatting
http://cldr.unicode.org/translation/date-time-patterns
http://cldr.unicode.org/translation/date-time-patterns

Download the raw XML data files here:
http://unicode.org/Public/cldr/28/core.zip

Look at core/common/main/en.xml (search for dateFormatItem and decimalFormats)

**Comment by gedw99** [comment]
any movement on this ?

**Comment by nicksnyder** [comment]
Not that I am aware of. If this is something that is of interest to you then feel free to work on it.

**Comment by abourget** [comment]
Yeah I'd be glad if you do :-)

**Comment by gedw99** [comment]
@nicksnyder 

Have you seen this ? Its handles l10n according to the readme.

https://github.com/maximilien/i18n4go
- is a full workflow, which i was looking for.
- is up to the language translation team to do it.   

Its using this repo as a dependency.

Seems to me like a great approach, and well done

**Comment by gedw99** [comment]
@abourget 
i am also starting work on this with another guy.

also there is some great best pracs here:
https://github.com/astaxie/build-web-application-with-golang/blob/master/en/10.1.md
about 6 pages, that i think we will fully integrate so everyone has options.

**Comment by gedw99** [comment]
weird. golang has first class support for using the cldr xml data
https://godoc.org/golang.org/x/text/unicode/cldr

funny that the golang team did not use this to create first class tooling for us already.

mhhh.... anyone knwo why ?

**Comment by joeybloggs** [comment]
Hello @nicksnyder @abourget and @ghost

I recently completed a package [locales](https://github.com/go-playground/locales) that may be of use. I created it for use in my own i18n package, but split the code into it's own repo in order for any other i18n or l10n package to use if they wanted.

My goal is to create a central package for locale information and formatting and have people wrap it as they wish.

All information is generated using the [CLDR](http://cldr.unicode.org/) rules and information.

It features:
- [x] Rules generated from the latest [CLDR](http://cldr.unicode.org/index/downloads) data, v29
- [x] Cardinal, Ordinal and Range Plural Rules
- [x] Month, Weekday and Timezone translations built in
- [x] Date & Time formatting functions
- [x] Number, Currency, Accounting and Percent formatting functions

I hope this can help 😄

**Comment by abourget** [comment]
Wow thats great! Thanks for sharing here.

**Comment by joeblew99** [comment]
Wondering what i should use now ?

this repo OR https://github.com/go-playground/universal-translator ?

**Comment by SCKelemen** [comment]
Is there any updates on this, or if no one is working on it, are there at least smaller bits of it that I could pick up and implement?

**Comment by joeybloggs** [comment]
I don't know if anyone is working on this @SCKelemen 

But in theory all that would have to be done to get l10n working in this project would be to map the locales from this library to the locales in https://github.com/go-playground/locales, which contains l10n functions.

**Comment by nicksnyder** [comment]
The focus of this library is translating messages.

For other types of localization check out http://golang.org/x/text or other 3rd party libraries mentioned in this thread.
