### ISSUE TITLE
Panic when re-running tool after string is removed

### ISSUE THREAD

**Issue by jcbwlkr** [nicksnyder/go-i18n#48]
I have an English file with strings `foo` and `bar`. I run the tool which generates a `de-DE.all.json` with empty translations for those strings. I removed the `foo` string from the English file and re-ran the tool intending to regenerate the German files and it panics.

```
~/project ᐳ cat en-US.all.json
[
  {
    "id": "bar",
    "translation": "Bar"
  }
]
~/project ᐳ cat de-DE.all.json
[
  {
    "id": "bar",
    "translation": ""
  },
  {
    "id": "foo",
    "translation": ""
  }
]
~/project ᐳ goi18n *all.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x50 pc=0x100afa]

goroutine 1 [running]:
github.com/nicksnyder/go-i18n/i18n/translation.(*singleTranslation).Backfill(0x82043a3a0, 0x0, 0x0, 0x0, 0x0)
        /Users/jwalker/go/src/github.com/nicksnyder/go-i18n/i18n/translation/single_translation.go:37 +0xba
main.(*mergeCommand).execute.func2(0x88205bc318, 0x82043a3a0, 0x0, 0x0)
        /Users/jwalker/go/src/github.com/nicksnyder/go-i18n/goi18n/merge.go:71 +0x11a
main.filter(0x820444de0, 0x820481b00, 0x0, 0x0, 0x0)
        /Users/jwalker/go/src/github.com/nicksnyder/go-i18n/goi18n/merge.go:100 +0x12e
main.(*mergeCommand).execute(0x820481ef0, 0x0, 0x0)
        /Users/jwalker/go/src/github.com/nicksnyder/go-i18n/goi18n/merge.go:69 +0xe11
main.main()
        /Users/jwalker/go/src/github.com/nicksnyder/go-i18n/goi18n/goi18n.go:78 +0x1ee
```

**Comment by nicksnyder** [comment]
Thanks for reporting. I am not sure when I will have time to look at this so I would greatly appreciate it if you (or anyone else) could take a look at submit a pull request to fix.

**Comment by Waitak** [comment]
Here's a solution:

$ git diff
diff --git a/i18n/translation/single_translation.go b/i18n/translation/single_translation.go
index 9fcba5a..a76c8c9 100644
--- a/i18n/translation/single_translation.go
+++ b/i18n/translation/single_translation.go
@@ -37,7 +37,7 @@ func (st *singleTranslation) Normalize(language *language.Language) Translation
 }
 
 func (st *singleTranslation) Backfill(src Translation) Translation {
-       if st.template == nil || st.template.src == "" {
+       if (st.template == nil || st.template.src == "") && src != nil {
                st.template = src.Template(language.Other)
        }
        return st
