### ISSUE TITLE
Failed to load translation

### ISSUE THREAD

**Issue by yazamiko** [nicksnyder/go-i18n#52]
![capture](https://cloud.githubusercontent.com/assets/1830728/19160723/54b25af4-8bc7-11e6-97aa-d4fb29103620.PNG)

I don't know what to do anymore.

**Comment by nicksnyder** [comment]
Are you new to go-i18n or have you been using it and it broke recently?

Looks like your shell isn't expanding `*`. What shell are you using?

go-i18n expects a list of actual files so if you shell doesn't automatically expand `*` then you need to explicitly pass a list of files.

**Comment by yazamiko** [comment]
Yes, I'm new to go-i18n. I'm using windows cmd.

**Comment by nicksnyder** [comment]
Windows doesn't automatically expand `*`. You will need to explicitly pass in each json file that you want goi18n to process.

`goi18n one.all.json two.all.json`

http://superuser.com/questions/460598/is-there-any-way-to-get-the-windows-cmd-shell-to-expand-wildcard-paths
