### ISSUE TITLE
Add HasFunc eqvlt to TFunc

### ISSUE THREAD

**Issue by mh-cbon** [nicksnyder/go-i18n#56]
Hi,

In one particular situation i want to translate some materials using a cascade of IDs.

Specifically for form error handling.

Reason for that is to be able to have a general translation, and if needed a set of more and more specific translations ID alternative for that specific (input + error) of that specific (form+input+error).

Right now i m doing it by trying to translate each possibility until it returns non empty value which is considered as the translation to consume.

I d prefer to use a `HasFunc(ID)` to remove that test on empty response.

what do you think ?

**Comment by nicksnyder** [comment]
So HasFunc would return a boolean true/false if a translation exists or not?

**Comment by mh-cbon** [comment]
yes. I also have been thinking to a sort of `CascadeTFunc(Ids []string, args ...interface{}) string` which has the advantage to better optimize the resources to find and identify the translation, see https://github.com/nicksnyder/go-i18n/blob/master/i18n/bundle/bundle.go#L224.

**Comment by nicksnyder** [comment]
Couple questions:

>  Right now i m doing it by trying to translate each possibility until it returns non empty value which is considered as the translation to consume. 
> I d prefer to use a HasFunc(ID) to remove that test on empty response.

Tfunc should return the translation id, not an empty response if a translation doesn't exist. Can you share your code?

> I also have been thinking to a sort of CascadeTFunc(Ids []string, args ...interface{}) string

If this function existed, would you still want/need HasFunc?

> has the advantage to better optimize the resources to find and identify the translation

I don't quite see how there is a better way than checking the ids one by one in priority order.

**Comment by mh-cbon** [comment]
1/ Right! mistake of mine.

```go
func (f *FormTranslator) TError(formName string, fErr *FormValidationError) template.HTML {
  ids := []string{
    strings.ToLower(formName+"-"+fErr.Field+"-"+fErr.Tag),
    strings.ToLower(fErr.Ns+"-"+fErr.Tag),
    strings.ToLower(fErr.Field+"-"+fErr.Tag),
    strings.ToLower("form_error-"+fErr.Tag),
  }
  for _,id := range ids {
    m := f.T(id, fErr) //todo, escape fErr.Value.
    if m!="" && m!=id {
      return template.HTML(m)
    }
  }
  return template.HTML(f.missingTranslation(formName, fErr))
}
```

2/ If this function existed, would you still want/need HasFunc?

no

3/ there is this [code](https://github.com/nicksnyder/go-i18n/blob/master/i18n/bundle/bundle.go#L225-L268) that would be redundant.

4/ btw, language detection could be handled into [TfuncAndLanguage](https://github.com/nicksnyder/go-i18n/blob/master/i18n/bundle/bundle.go#L187), no ?

**Comment by nicksnyder** [comment]
I think this will be solved/obsolete with v2 proposed in #92

**Comment by mh-cbon** [comment]
sure, thanks.

**Comment by nicksnyder** [comment]
I just tagged [2.0.0.beta.1](https://github.com/nicksnyder/go-i18n/releases/tag/v2.0.0.beta.1). Please start using it and report any issues that you have.
