### ISSUE TITLE
feature request: Arb format for strings

### ISSUE THREAD

**Issue by joeblew99** [nicksnyder/go-i18n#57]
I was wondering if we can support ARB format, so i can use google translate toolkit.

Here is a good summary:
https://github.com/dart-lang/intl#extracting-and-using-translated-messages

Background info:
At the moment i use Dart for frontend and golang for backend.

**Comment by nicksnyder** [comment]
I clicked through the links and couldn't find an example of what an ARB file looks like or a spec for the ARB format. If you know where these are can you share?

**Comment by joeblew99** [comment]
thanks for considering this feature. 
I think it is pretty nice wy to share translations between frontend and backend.

I looked around for some examples of ARB.

This is a good example i think.
https://github.com/flutter/flutter/tree/master/examples/stocks/lib/i18n
https://github.com/flutter/flutter/blob/2a81391915a5b223279f117d9143ed483b8482e4/examples/stocks/lib/stock_strings.dart


Also running Dart is very easy. Brew install it and it will do everything, and then "pub get". like "go get".

**Comment by nicksnyder** [comment]
Hmm, it doesn't look like this format supports plural forms so I don't think it is an appropriate format for what go-i18n does. If you only want to store your translations in one format, I would write a script to translate from one to the other.

**Comment by joeblew99** [comment]
make sense. I will do it myself. DO you want a patch ? Its ok if you dont..

**Comment by nicksnyder** [comment]
Probably not, thanks for offering though.

I am going to go ahead and close this issue.
