### ISSUE TITLE
isStandardFormat() incorrectly returns false if yaml file starts with a comment

### ISSUE THREAD

**Issue by tabacco** [nicksnyder/go-i18n#70]
It looks like the recent change to support a flatter format might have some backwards-compatibility issues with yaml

https://github.com/nicksnyder/go-i18n/blob/master/i18n/bundle/bundle.go#L125

This line assumes that a standard format yaml file will start with a ```-```, which is true unless there's a comment at the start of the file. In that case, it'll assume it's a flat format file and panic/error.

**Comment by nicksnyder** [comment]
Can you give an example file that is failing?

You can see here that we do try/intend to strip out leading comments.
https://github.com/nicksnyder/go-i18n/blob/master/i18n/bundle/bundle.go#L123

cc @bogem

**Comment by bogem** [comment]
We also have [tests](https://github.com/nicksnyder/go-i18n/commit/7e6a19b81bf3b5a1b480fd176a853b2ac4803be5#diff-00fdb15b43cd4495854d41c9da996781), that even start with 2 newlines and comments.

**Comment by nicksnyder** [comment]
It was fixed in HEAD but not in the latest release (1.8). I just released 1.8.1 which should solve your problem @tabacco

**Comment by tabacco** [comment]
Excellent, thanks @nicksnyder!
