### ISSUE TITLE
go-i18n fails on custom language codes

### ISSUE THREAD

**Issue by bogem** [nicksnyder/go-i18n#72]
If user wants to have custom language code that aren't in [Unicode CLDR](http://www.unicode.org/cldr/charts/28/supplemental/language_plural_rules.html) (like at.yaml, dk.yaml, ch.yaml, gb.yaml, etc.), `bundle.ParseTranslationFileBytes` returns `no language found in "dk.yaml"`.
I don't think that users should be limited only with CLDR languages. They can freely use language codes they want and it can be technically implemented.
Discussion: https://discuss.gohugo.io/t/i18n-country-codes-as-part-of-the-url/6881

**Comment by bep** [comment]
I agree. In Hugo we use this language code as part of the URL in a multisite setup, and I have always assumed that I could abuse this feature to make multisite setups of whatever term I want, even non-languages. And even if we do restrict it to languages, I don't see why `go-i8n` should stop me from creating my own custom language.

**Comment by nicksnyder** [comment]
This sounds reasonable to me and it probably isn't that difficult.

You might only need to export [registerPluralSpec](https://sourcegraph.com/github.com/nicksnyder/go-i18n@3e70a1a463008cea6726380c908b1a6a8bdf7b24/-/blob/i18n/language/pluralspec.go#L21:18). Then during your application's initialization register whatever language ids you want.

**Comment by bogem** [comment]
> You might only need to export registerPluralSpec. Then during your application's initialization register whatever language ids you want.

I have an idea to make it simpler and without exporting something. Hopefully it will work.

**Comment by bogem** [comment]
Related lines: https://github.com/nicksnyder/go-i18n/blob/master/i18n/language/language.go#L61-L63

**Comment by bogem** [comment]
Ping

**Comment by nicksnyder** [comment]
I merged https://github.com/nicksnyder/go-i18n/pull/79 which exports Operands and RegisterPluralSpec. I think this should unblock you.
