### ISSUE TITLE
Support contextual comments for translations

### ISSUE THREAD

**Issue by nicksnyder** [nicksnyder/go-i18n#8]
Comments are useful for translators so they can understand additional context about the translation.

``` json
{
  "id": "helloName",
  "translation": "Hello {{name}}",
  "comment": "This is a welcome message for a user. {{name}} is the user's first name."
}
```

**Comment by parkr** [comment]
I dig this. Need any help here?

**Comment by nicksnyder** [comment]
@parkr I haven't started working on this and probably won't anytime soon. Would you like to do this?

**Comment by abourget** [comment]
How complex can that be ?!

**Comment by abourget** [comment]
I could give it a shot if it's just adding a field to a struct :)

**Comment by nicksnyder** [comment]
@abourget It might be more complicated than simply adding a field to the struct. I forget why I didn't just do this to begin with. Feel free to work on this and submit a pull request.

**Comment by nicksnyder** [comment]
This will be possible in v2. See also https://github.com/nicksnyder/go-i18n/pull/92

**Comment by nicksnyder** [comment]
I just tagged [2.0.0.beta.1](https://github.com/nicksnyder/go-i18n/releases/tag/v2.0.0.beta.1). Please start using it and report any issues that you have.
