### ISSUE TITLE
Support short language tags

### ISSUE THREAD

**Issue by tdewolff** [nicksnyder/go-i18n#9]
Does not support single subtag IETF language codes or anything else but 2-subtag codes, while the IETF language code does define other-than-2-subtag syntax.

Since browsers often send short IETF language tags, this doesn't really work with go-i18n. For example, my browser sends: `Accept-Language:en-US,en;q=0.8,de;q=0.6,nl;q=0.4`. Only the `en-US` is useful for go-i18n, but `en`/`de`/`nl` are not.

It would be great if you request en-US with i18n.Tfunc and only `en` exists, it uses `en`. This can be extended when any request for a more specific language tag (more extensions) is boiled down to the closest supported language tag

**Comment by nicksnyder** [comment]
I got around to fixing this :)

Let me know if you see any issues.
