### ISSUE TITLE
unescaped HTML fragments?

### ISSUE THREAD

**Issue by hybernaut** [nicksnyder/go-i18n#90]
Is it possible to write translation strings for html/template templates which contain HTML fragments?

For example:
```
  {
    "id": "userUnauthorized",
    "translation": "You are not authorized to view user <span class='entityName'>{{ .userName }}</span>. "
  },
```

Calling `{{T "userUnauthorized" .}}` results in escaped HTML.  I would prefer to use HTML in my translations because it reduces the total number of keys required, and I want to give my translators more flexibility with sentence construction.

If I were using `html/template` directly, I could use the `template.HTML` function to declare that the input is HTML and not a string. Is there a clean way to use something like this technique for translations?

**Comment by nicksnyder** [comment]
> Calling {{T "userUnauthorized" .}} results in escaped HTML.

Are you sure? I don't think this should be the case.

[go-i18n uses test/template](https://github.com/nicksnyder/go-i18n/blob/master/i18n/translation/template.go#L7), not html/template, so [nothing should get escaped](https://play.golang.org/p/ZqIM5L-myaq) afaik.

It looks like you are calling the T func inside of a template that is probably getting executed in a `html/template`, and that is what is doing the escaping.

**Comment by hybernaut** [comment]
yes, I'm definitely trying to use translations in templates--that's where most of my user-visible strings are.  I'll look and see if I can find a workaround at that level, thanks.

**Comment by hybernaut** [comment]
As a followup, I have been using this form for the last year:
```
    <p>  {{ T "userUnauthorized" . | safeHTML }}  </p>
```
