### ISSUE TITLE
The goroutine safety of Tfunc and AddTranslation functions

### ISSUE THREAD

**Issue by namco1992** [nicksnyder/go-i18n#91]
Hi,

Thank you for creating this great tool!

I'm using the `go-i18n` with the `PhraseApp`, which is a platform that provides the API to download the translated file. I want to reload the translated file on the fly when the translators do some changes without re-deploying our microservices.

I noticed that the `AddTranslation` method can import the translations and it will apply the lock to the bundle, but I also noticed that you mentioned that "Your Go program should load translations during its initialization". So I wonder that if it's appropriate to reload the translations after the service initialization using `AddTranslation`.

The second question is about the goroutine safety of `Tfunc`. Is it safe that I get a `Tfunc` during the initialization and use it as a global sharing function? From my understanding, it should be ok. I just wanna confirm it here.

Thank you again.

**Comment by nicksnyder** [comment]
> Your Go program should load translations during its initialization

The library was originally designed without concurrency in mind. It assumed that you loaded everything during initialization and then used TFunc after that.

https://github.com/nicksnyder/go-i18n/pull/59 added support for concurrency so what you are trying to do should work, but I would verify by running the race detector.

> Is it safe that I get a Tfunc during the initialization and use it as a global sharing function

I don't see anything wrong with that.

**Comment by namco1992** [comment]
Thank you very much for the reply, it helps a lot.
