### ISSUE TITLE
Cannot use % within an arg (template data) to the translate func

### ISSUE THREAD

**Issue by jhart1685** [nicksnyder/go-i18n#93]
I've spent a few hours trying to figure this out, but it looks like it is not possible for an argument (/insert) on a call to i18n.T to contain a percent character.

anonymized code:
```
func main() {
	input := "%"
	fmt.Printf(i18n.T("<my translation ID>",
		map[string]interface{}{
			"Insert": input,
		}))
}
``` 

Output (with preceding message text removed):
```
%! (MISSING)
```

I've tried substituting % with %25 , url escaping , passing in as byte slice rather than string.

But it looks like a percent anywhere within a value (of the args template data) gets garbled.

**Comment by nicksnyder** [comment]
What does the translation for `<my translation ID>` look like?

I am not able to reproduce this with the information you have given me.

For example, this test passes:
```go
func ExamplePercent() {
	i18n.ParseTranslationFileBytes("en-us.all.json", []byte(`[
{
	"id": "hello_person",
	"translation": "hello {{.Person}}"
}
]`))

	T, _ := i18n.Tfunc("en-us")
	fmt.Println(T("hello_person", map[string]interface{}{
		"Person": "%",
	}))
	// Output:
	// hello %
}
```

If you can write a failing test, the would be the most helpful.

**Comment by jhart1685** [comment]
Hi @nicksnyder - thanks for the quick response.
Apologies - this was user error. The difference between your test and mine was that yours wrote the output with `Println()`, while I used `Printf()` without a format. The returned string from the translate func was correct - but it got mangled by my misuse of Printf.
