### ISSUE TITLE
detect user locale ?

### ISSUE THREAD

**Issue by gedw99** [nicksnyder/go-i18n#94]
see https://github.com/getlantern/i18n

We coudl incorporate the ability to pick detect the users locale. I need this for Desktop apps :)

**Comment by nicksnyder** [comment]
That project doesn't do anything special. It just reads an environment variable and your application can do the same (and then pass it to go-i18n).

https://github.com/getlantern/jibber_jabber/blob/7346f98d2644252b9fc10b89af1f1858b2dc29b9/jibber_jabber_unix.go#L11-L17

go-i18n doesn't know if it is being used in the context of a desktop app or a web app, so figuring out which locale to use it not in scope for this library.
